/**
 * Rebuilds data/program-galleries.ts from files already on disk.
 * Usage: npx tsx scripts/rebuild-program-galleries.ts
 */
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(process.cwd());
const OUT_DIR = join(ROOT, "public", "images", "awfca", "programs");
const DATA_FILE = join(ROOT, "data", "program-galleries.ts");
const MAX = 20;

const SLUGS = [
  "orphan-support-program",
  "student-scholarship-breaking-barriers-building-futures",
  "computer-training-institute",
  "mobile-health-unit",
  "new-beginnings-program",
  "collective-qurbani-project",
  "emergency-relief-fund",
  "zakaat-fund",
  "sadaqah-tul-fitr",
  "fidyaa",
  "clean-water-project",
  "food-bank",
  "free-medical-dispensary",
  "ramadan-hamper",
  "eid-gift-hampers",
  "helping-hands-campaign",
  "gaza-dignity-kits",
];

const galleries: Record<string, string[]> = {};

for (const slug of SLUGS) {
  const dir = join(OUT_DIR, slug);
  galleries[slug] = existsSync(dir)
    ? readdirSync(dir)
        .filter((name) => /\.(jpe?g|png|webp)$/i.test(name))
        .sort()
        .slice(0, MAX)
        .map((name) => `/images/awfca/programs/${slug}/${name}`)
    : [];
  console.log(`${slug}: ${galleries[slug].length}`);
}

writeFileSync(
  DATA_FILE,
  `/** Auto-generated by scripts/import-program-galleries.ts — do not edit by hand. */\nexport const programGalleries: Record<string, string[]> = ${JSON.stringify(
    galleries,
    null,
    2,
  )};\n`,
  "utf8",
);

console.log(`Wrote ${DATA_FILE}`);
